spring:
  datasource:
    url: jdbc:mysql://172.27.115.44:3306/luck-shop?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: hanye@123456
  redis:
    database: 2
    host: 172.27.115.44
    port: 6379
    #password: 123456
#  rabbitmq:
#    host: 172.27.115.44
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#
#  cloud:
#    stream:
#      bindings:
#        synchronous-order-consumer:
#          destination: synchronous-order--topic
#        synchronous-order-producer:
#          destination: synchronous-order--topic

    zipkin:
      base-url: http://172.27.115.44:9411/
      locator:
        discovery:
          enabled: true
        # 以HTTP上传数据到Zipkin
        # WHY? bus依赖项导入了rabbitmq的依赖项，zipkin会默认使用mq
      sender:
        type: web
      sleuth:
        sampler:
          probability: 1


eureka:
  client:
    service-url:
      defaultZone: http://172.27.115.44:20000/eureka/
  instance:
    instance-id: ${erueka.instance.ip-address}:${server.port}
    ip-address: 172.27.115.44
    prefer-ip-address: true


elastic:
  job:
    zk:
      namespace: elastic-job
      serverLists: 118.190.159.184:2181