############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 10002
spring:
  datasource:
    url: jdbc:mysql://118.190.159.184:3306/fun-box?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: hanye@123456
  redis:
    database: 1
    host: 118.190.159.184
    port: 6379
    #password: 123456

  zipkin:
    base-url: http://118.190.159.184:9411/
    locator:
      discovery:
        enabled: true
      # 以HTTP上传数据到Zipkin
      # WHY? bus依赖项导入了rabbitmq的依赖项，zipkin会默认使用mq
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1




eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/



elastic:
  job:
    zk:
      namespace: elastic-job
      serverLists: 118.190.159.184:2181