############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 10007
spring:
  datasource:
    url: jdbc:mysql://192.168.0.61:3306/fun-box?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: hanye@123456
  redis:
    database: 1
    host: 192.168.0.61
    port: 6379
    #password: 123456

  zipkin:
    base-url: http://192.168.0.61:9411/
    locator:
      discovery:
        enabled: true
      # 以HTTP上传数据到Zipkin
      # WHY? bus依赖项导入了rabbitmq的依赖项，zipkin会默认使用mq
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1




